name: Build and Upload Supremacy Hangar

on:
    workflow_dispatch: {}

jobs:
    build:
        runs-on: [self-hosted, windows, x64]
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: "0"
                  lfs: true

            - name: Prewarm
              run: Start-Process -FilePath "C:\actions-runner\_work\supremacy-hangar\supremacy-hangar\prewarm.bat" -Wait -WindowStyle Hidden

            - name: Build
              run: Start-Process -FilePath "C:\actions-runner\_work\supremacy-hangar\supremacy-hangar\build.bat" -Wait -WindowStyle Hidden

    deploy:
        needs: [build]
        runs-on: [self-hosted, windows, x64]
        steps:
            - name: Synchronize
              run: |
                  winscp "scp://${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" /privatekey=C:\etc\ssh\build_machine.ppk -hostkey="${{ secrets.SSH_HOSTKEY }}" /command "synchronize remote -mirror C:\actions-runner\_work\supremacy-hangar\supremacy-hangar\Builds\WebGL\ /var/www/html/supremacy-hangar/dev-build/" "exit"
