name: Build and Upload Supremacy Hangar

on:
    workflow_dispatch: {}

jobs:
    checkout:
        - name: Checkout Repository
        runs-on: [self-hosted, linux, x64]
        steps:
            uses: actions/checkout@v2
            with:
                lfs: true

            # Git LFS
            - name: Git LFS Pull
              run: |
                  git lfs pull
                  git add .
                  git reset --hard
    prewarm:
        - name: Prewarm Project
        runs-on: [self-hosted, linux, x64]
        needs: [checkout]
        steps: 
            run: |
                echo $(pwd)
                cd ~/actions-runner/_work/${{ github.event.repository.name }}/${{ github.event.repository.name }}
                ~/Unity/Hub/Editor/2021.3.4f1/Editor/Unity -batchmode -quit -buildTarget WebGL -logFile log.txt  -executeMethod BuildSystem.CLI.PreWarm
    build:
        - name: Build Project
        runs-on: [self-hosted, linux, x64]
        needs: [checkout, prewarm]
        steps:
            run: |
                echo $(pwd)
                cd ~/actions-runner/_work/${{ github.event.repository.name }}/${{ github.event.repository.name }}
                ~/Unity/Hub/Editor/2021.3.4f1/Editor/Unity -batchmode -quit -buildTarget WebGL -logFile log.txt -executeMethod BuildSystem.CLI.BuildWebGL -development
                # Zip Build

    upload:
        - name: Build Project
        runs-on: [self-hosted, linux, x64]
        needs: [checkout, prewarm, build]
        steps:
            - name: Zip Build
              run: |
                  echo $(pwd)
                  cd ~/actions-runner/_work/${{ github.event.repository.name }}/${{ github.event.repository.name }}
                  pushd Builds/WebGL
                  zip -r ../../build-v${{ github.run_number }}.zip .
                  popd

            # Rsync to aflies.server
            - name: Rsync to afiles.ninja
              run: rsync -av build-v${{ github.run_number }}.zip ${{ secrets.AFILES_SSH_HOST }}:/var/www/html/supremacy-hangar/
