# This is a basic workflow to help you get started with Actions

name: build-deploy-testapp

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the "develop" branch
    push:
        branches: ["develop"]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: [self-hosted]

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v3

            # set up Unity version requirement
            - name: Setup Unity
              uses: kuler90/setup-unity@v1
              with:
                  unity-version: 2021.3.3f1
                  unity-modules: webgl

            # build Unity
            - name: Build Unity
              run: |
                  "C:\Program Files\Unity\Hub\Editor\2021.3.4f1\Editor\Unity.exe" -batchmode -quit -buildTarget WebGL -projectPath "C:\Ninja\Documents\supremacy-hangar" -logFile log.txt -executeMethod BuildSystem.CLI.PreWarm
                  "C:\Program Files\Unity\Hub\Editor\2021.3.4f1\Editor\Unity.exe" -batchmode -quit -buildTarget WebGL -projectPath "C:\Ninja\Documents\supremacy-hangar" -logFile log.txt -executeMethod BuildSystem.CLI.BuildWebGL -development
