name: Build and Upload Supremacy Hangar

on:
    workflow_dispatch: {}

jobs:
    build-upload:
        runs-on: [self-hosted, linux, x64]
        steps:
            # Checkout repository
            - name: Checkout Repository
              uses: actions/checkout@v2
              with:
                  lfs: true

            # Git LFS
            - name: Git LFS Pull
              run: |
                  git lfs pull
                  git add .
                  git reset --hard

            # Build
            - name: Build Unity Project
              run: |
                  cd ~/actions-runner/_work/${{ github.event.repository.name }}/${{ github.event.repository.name }}
                  ~/Unity/Hub/Editor/2021.3.4f1/Editor/Unity -batchmode -quit -buildTarget WebGL -logFile log.txt  -executeMethod BuildSystem.CLI.PreWarm
                  ~/Unity/Hub/Editor/2021.3.4f1/Editor/Unity -batchmode -quit -buildTarget WebGL -logFile log.txt -executeMethod BuildSystem.CLI.BuildWebGL -development
                  # Zip Build

            - name: Zip Build
              run: |
                  pushd Builds/WebGL
                  zip -r ../../build-v${{ github.run_number }}.zip .
                  popd

            # Rsync to aflies.server
            - name: Rsync to afiles.ninja
              run: rsync -av build-v${{ github.run_number }}.zip ${{ secrets.AFILES_SSH_HOST }}:/var/www/html/supremacy-hangar/
