name: Build and Upload Supremacy Hangar

on:
    workflow_dispatch: {}

jobs:
    build-upload:
        runs-on: [self-hosted]
        steps:
            # Checkout without LFS
            - name: Checkout Repository
              uses: actions/checkout@v2

            # Git LFS
            - name: Git LFS Pull
              run: |
                  git lfs pull
                  git add .
                  git reset --hard

            # Build
            - name: Build Unity Project
              run: |
                  Set-Location -Path "C:\actions-runner\_work\supremacy-hangar\supremacy-hangar"
                  Start-Process -FilePath "C:\actions-runner\_work\supremacy-hangar\supremacy-hangar\prewarm.bat" -Wait -WindowStyle Hidden
                  Start-Process -FilePath "C:\actions-runner\_work\supremacy-hangar\supremacy-hangar\build.bat" -Wait -WindowStyle Hidden
