name: Dev Build CI

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: [ self-hosted, windows, x64 ]
    steps:
      # Checkout (without LFS)
      - name: Checkout repository
        uses: actions/checkout@v2

      # Git LFS
      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v3
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Prewarm
        run: |
          $unityPath="C:\Program Files\Unity\Hub\Editor\2021.3.4f1\Editor\Unity.exe"
          $projectPath="C:\actions-runner\_work\supremacy-hangar\supremacy-hangar"
          Start-Process -FilePath $unityPath -ArgumentList "-batchmode -quit -buildTarget WebGL -projectPath $projectPath -logFile prewarm_log.txt -executeMethod BuildSystem.CLI.PreWarm -addressablesLocation dev" -Wait -WindowStyle Hidden

      - name: Build
        run: |
          $unityPath="C:\Program Files\Unity\Hub\Editor\2021.3.4f1\Editor\Unity.exe"
          $projectPath="C:\actions-runner\_work\supremacy-hangar\supremacy-hangar"
          Start-Process -FilePath $unityPath -ArgumentList "-batchmode -quit -buildTarget WebGL -projectPath $projectPath -logFile builds_log.txt -executeMethod BuildSystem.CLI.BuildWebGL -addressablesLocation dev" -Wait -WindowStyle Hidden

  deploy-build:
    runs-on: [ self-hosted, windows, x64 ]
    steps:
      - name: Synchronize Build
        run: |
          $projectPath = "C:\actions-runner\_work\supremacy-hangar\supremacy-hangar"
          New-Item -Path "$projectPath" -Name "BuildB" -ItemType "directory"
          Copy-Item "$projectPath\Builds\WebGL\Build\*" -Destination "$projectPath\BuildB" -Recurse
          Copy-Item "$projectPath\Builds\WebGL\StreamingAssets" -Destination "$projectPath\BuildB" -Recurse
          $runnerHome = "/cygdrive/c/users/${{ secrets.RUNNER_USER }}"
          $cygdriveProjectPath = "/cygdrive/c/actions-runner/_work/supremacy-hangar/supremacy-hangar"
          rclone sync " $cygdriveProjectPath/BuildB/" "${{secrets.RCLONE_USER}}:/var/www/html/supremacy-hangar/build/develop/$GITHUB_HEAD_REF-$GITHUB_RUN_ATTEMPT" --progress --verbose --multi-thread-streams 4
  deploy-addressables:
    runs-on: [ self-hosted, windows, x64 ]
    steps:
      - name: Synchronize Addressables
        run: |
          $projectPath = "C:\actions-runner\_work\supremacy-hangar\supremacy-hangar"
          $runnerHome = "/cygdrive/c/users/${{ secrets.RUNNER_USER }}"
          $cygdriveProjectPath = "/cygdrive/c/actions-runner/_work/supremacy-hangar/supremacy-hangar"
          rclone sync " $cygdriveProjectPath/ServerData/" "${{secrets.RCLONE_USER}}:/var/www/html/supremacy-hangar/addressables/develop/" --progress --verbose --multi-thread-streams 4
