name: Production CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [ self-hosted, windows, x64 ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"
          lfs: true

      - name: Prewarm
        run: |
          $unityPath="C:\Program Files\Unity\Hub\Editor\2021.3.4f1\Editor\Unity.exe"
          $projectPath="C:\actions-runner\_work\supremacy-hangar\supremacy-hangar"
          Start-Process -FilePath $unityPath -ArgumentList "-batchmode -quit -buildTarget WebGL -projectPath $projectPath -logFile prewarm_log.txt -executeMethod BuildSystem.CLI.PreWarm -addressablesLocation prod" -Wait -WindowStyle Hidden

      - name: Build
        run: |
          $unityPath="C:\Program Files\Unity\Hub\Editor\2021.3.4f1\Editor\Unity.exe"
          $projectPath="C:\actions-runner\_work\supremacy-hangar\supremacy-hangar"
          Start-Process -FilePath $unityPath -ArgumentList "-batchmode -quit -buildTarget WebGL -projectPath $projectPath -logFile build_log.txt -executeMethod BuildSystem.CLI.BuildWebGL -addressablesLocation prod" -Wait -WindowStyle Hidden

  deploy-build:
    needs: [ build ]
    runs-on: [ self-hosted, windows, x64 ]
    steps:
      - name: Synchronize Build
        run: |
          $projectPath = "C:\actions-runner\_work\supremacy-hangar\supremacy-hangar"
          New-Item -Path "$projectPath" -Name "BuildB" -ItemType "directory"
          Copy-Item "$projectPath\Builds\WebGL\Build\*" -Destination "$projectPath\BuildB" -Recurse
          Copy-Item "$projectPath\Builds\WebGL\StreamingAssets" -Destination "$projectPath\BuildB" -Recurse
          rclone sync "$projectPath/BuildB/" "afiles:/var/www/html/supremacy-hangar/build/production/" --progress --verbose --multi-thread-streams 4
  deploy-addressables:
    needs: [ build ]
    runs-on: [ self-hosted, windows, x64 ]
    steps:
      - name: Synchronize Addressables
        run: |
          $projectPath = "C:\actions-runner\_work\supremacy-hangar\supremacy-hangar"
          rclone sync "$projectPath/ServerData/" "afiles:/var/www/html/supremacy-hangar/addressables/production/" --progress --verbose --multi-thread-streams 4
  purge-cache:
    needs: [deploy-build]
    runs-on: [self-hosted, windows, x64]
    steps:
      - name: Purging Cloudflare Cache
        env:
          CLOUDFLARE_AUTH_EMAIL: ${{ secrets.CloudflareAuthEmail }}
          CLOUDFLARE_AUTH_KEY: ${{ secrets.CloudflareAuthKey }}
          CLOUDFLARE_IDENTIFIER: ${{ secrets.CloudflareIdentifier }}
        run: |
          cmd.exe /c 'curl.exe -H "X-Auth-Email: %CLOUDFLARE_AUTH_EMAIL%" -H "X-Auth-Key: %CLOUDFLARE_AUTH_KEY%" -H "Content-Type: application/json"  -d "{\"files\": [\"https://afiles.ninja-cdn.com/supremacy-hangar/build/production/WebGL.loader.js\",\"https://afiles.ninja-cdn.com/supremacy-hangar/build/production/WebGL.data.br\", \"https://afiles.ninja-cdn.com/supremacy-hangar/build/production/WebGL.framework.js.br\",\"https://afiles.ninja-cdn.com/supremacy-hangar/build/production/WebGL.wasm.br\",\"https://afiles.ninja-cdn.com/supremacy-hangar/build/production/StreamingAssets\"]}" "https://api.cloudflare.com/client/v4/zones/%CLOUDFLARE_IDENTIFIER%/purge_cache"'          
