name: Staging CI

on:
  push:
    branches: ["develop"]

jobs:
  build:
    runs-on: [self-hosted, windows, x64]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"
          lfs: true

      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Prewarm
        run: |
          $unityPath="C:\Program Files\Unity\Hub\Editor\2021.3.4f1\Editor\Unity.exe"
          $projectPath="C:\actions-runner\_work\supremacy-hangar\supremacy-hangar"
          Start-Process -FilePath $unityPath -ArgumentList "-batchmode -quit -buildTarget WebGL -projectPath $projectPath -logFile prewarm_log.txt -executeMethod BuildSystem.CLI.PreWarm -addressablesLocation staging" -Wait -WindowStyle Hidden

      - name: Build
        run: |
          $unityPath="C:\Program Files\Unity\Hub\Editor\2021.3.4f1\Editor\Unity.exe"
          $projectPath="C:\actions-runner\_work\supremacy-hangar\supremacy-hangar"
          Start-Process -FilePath $unityPath -ArgumentList "-batchmode -quit -buildTarget WebGL -projectPath $projectPath -logFile build_log.txt -executeMethod BuildSystem.CLI.BuildWebGL -addressablesLocation staging" -Wait -WindowStyle Hidden

  deploy-build:
    needs: [build]
    runs-on: [self-hosted, windows, x64]
    steps:
      - name: Synchronize Build
        run: |
          $projectPath = "C:\actions-runner\_work\supremacy-hangar\supremacy-hangar"
          New-Item -Path "$projectPath" -Name "BuildB" -ItemType "directory"
          Copy-Item "$projectPath\Builds\WebGL\Build\*" -Destination "$projectPath\BuildB" -Recurse
          Copy-Item "$projectPath\Builds\WebGL\StreamingAssets" -Destination "$projectPath\BuildB" -Recurse
          rclone sync " $projectPath/BuildB/" "afiles:/var/www/html/supremacy-hangar/build/staging/" --progress --verbose --multi-thread-streams 4
  deploy-addressables:
    needs: [build]
    runs-on: [self-hosted, windows, x64]
    steps:
      - name: Synchronize Addressables
        run: |
          $projectPath = "C:\actions-runner\_work\supremacy-hangar\supremacy-hangar"
          rclone sync " $projectPath/ServerData/" "afiles:/var/www/html/supremacy-hangar/addressables/staging/" --progress --verbose --multi-thread-streams 4
