name: Acquire Activation File
on:
    [push]
jobs:
    activation:
        runs-on: [ self-hosted, windows, x64 ]
        steps:
            - name: Test github run number
              run: |
                echo "This is the run number ${{env.GITHUB_RUN_ATTEMPT}}"